package pj1;

/**
 * https://projecteuler.net/problem=2
 * 
 * 
 * java Each new term in the Fibonacci sequence is generated by adding the
 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1,2,3,5,8,... By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued terms.
 * 
 * @author engels
 *
 */
public class FibonacciSum {
	public static void main(String[] args) {
		fibSum();
	}

	private static void fibSum() {
		int limit = 4000000;
		int sum = 0;
		int previousTerm = 1;
		int currentTerm = 2;

		while (currentTerm <= limit) {
			if (currentTerm % 2 == 0) {
				sum += currentTerm;
			}

			int nextTerm = previousTerm + currentTerm;
			previousTerm = currentTerm;
			currentTerm = nextTerm;
		}

		System.out.println("Sum of even-valued terms: " + sum);
		/*
		 * 
		 * Sum of even-valued terms: 4613732
		 * 
		 * 
		 * Congratulations, the answer you gave to problem 2 is correct.
		 * 
		 * The public tables currently show that this problem has been solved by 774549
		 * members.
		 * 
		 * This problem has a difficulty rating of 5%. The highest difficulty rating you
		 * had previously solved was 0%. This is a new record. Well done!
		 * 
		 * Not enough data to determine solve metrics.
		 */
	}
}